stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: php:7.3-apache
      shellScript: |-
        apt-get update
        cp config/app.default.php config/app.php
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cake-example:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
