stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: php:7.3
      shellScript: |-
        apt-get update
        apt-get install -y --no-install-recommends git zip libsqlite3-dev zlib1g-dev
        apt-get update -yqq && apt-get install -y libxml2-dev libicu-dev libfreetype6-dev libmcrypt-dev libjpeg62-turbo-dev libcurl4-gnutls-dev libbz2-dev libssl-dev libpq-dev libxslt1.1 libxslt1-dev libzip-dev -yqq
        docker-php-ext-install pdo_pgsql
        docker-php-ext-install pgsql
        docker-php-ext-install json
        docker-php-ext-install bcmath
        docker-php-ext-install mbstring
        docker-php-ext-install intl
        docker-php-ext-install zip
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
        docker-php-ext-install gd

        curl --silent --show-error https://getcomposer.org/installer | php
        ./composer.phar install -n --prefer-dist
        cp config/app.default.php config/app.php
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: cake-example:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
