kind: Service
apiVersion: v1
metadata:
  name: cake-example
spec:
  selector:
    app: cake-example
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cake-example
  labels:
    app: cake-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cake-example
  template:
    metadata:
      labels:
        app: cake-example
    spec:
      imagePullSecrets:
      - name: nexus
      containers:
      - name: cake
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
